name: Android Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/react-native-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup JDK Zulu 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Build Android
        run: ./gradlew assemble
        working-directory: packages/react-native-app/android
