name: Build Expo iOS

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ./packages/expo-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Expo iOS
        run: yarn ios
