name: iOS Build & Detox

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ./packages/react-native-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Pod Dependencies
        run: cd ios && pod --version && pod install

      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Build for Detox
        run: yarn detox build -c ios.sim.release

      - name: Test with Detox
        run: yarn detox test --debug-synchronization 200 -c ios.sim.release
