name: Build React Native Android

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/react-native-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Azul Zulu OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Build Android
        run: ./gradlew assemble
        working-directory: packages/react-native-app/android
