name: On Push
on: [push, pull_request]

jobs:
  lint_test_generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install --immutable --check-cache

      - name: Lint with ESLint
        run: yarn lint:eslint

      - name: Lint with TSC
        run: yarn lint:tsc

      - name: Run test with Jest
        run: yarn test

      - name: Generate
        run: yarn generate

      - name: Pack (to ensure the plugin builds)
        run: yarn pack

    outputs:
      NVMRC: ${{ steps.nvm.outputs.NVMRC }}

  call_android_workflow:
    needs: lint_test_generate
    uses: ./.github/workflows/android-actions.yml
    with:
      NVMRC: ${{ needs.lint_test_generate.outputs.NVMRC }}

  call_ios_workflow:
    needs: lint_test_generate
    uses: ./.github/workflows/ios-actions.yml
    with:
      NVMRC: ${{ needs.lint_test_generate.outputs.NVMRC }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [lint_test_generate, call_android_workflow, call_ios_workflow]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.lint_test_generate.outputs.NVMRC }}
          registry-url: https://registry.npmjs.org/

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install --immutable --check-cache

      - name: Setup .yarnrc.yml
        run: yarn config set npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}

      - name: Publish
        run: yarn npm publish
