name: Review

on:
  workflow_call:
    # Release calls this Workflow
  pull_request:
    branches:
      - main
      - beta
      - alpha
  merge_group:
    types:
      - checks_requested

jobs:
  lint-tsc:
    name: Lint TSC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint with TSC
        run: yarn lint:tsc

      - name: Lint Plugin with TSC
        run: yarn plugin:lint:tsc

  lint-eslint:
    name: Lint ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint with ESLint
        run: yarn lint:eslint

      - name: Lint Plugin with ESLint
        run: yarn plugin:lint:eslint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test with Jest
        run: yarn test

      - name: Test Plugin with Jest
        run: yarn plugin:test

  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Codegen
        run: yarn codegen

  build-library:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Library
        run: yarn prepack

  build-react-native-android:
    name: Build React Native Android
    needs: [lint-eslint, lint-tsc, test, codegen, build-library]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Azul Zulu OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Build Android
        working-directory: ./packages/react-native-app
        run: yarn react-native build-android

  build-react-native-ios:
    name: Build React Native iOS & Test with Maestro
    needs: [lint-eslint, lint-tsc, test, codegen, build-library]
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Maestro
        working-directory: ./packages/react-native-app
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Install Pods
        working-directory: ./packages/react-native-app
        run: yarn pod:install

      - name: Build iOS
        working-directory: ./packages/react-native-app
        run: xcodebuild -workspace ios/MapLibreReactNativeExample.xcworkspace -scheme MapLibreReactNativeExample -configuration Release -sdk iphonesimulator -derivedDataPath ios/build

      - name: Install on iOS Simulator
        working-directory: ./packages/react-native-app
        run: |
          xcrun simctl boot "iPhone 15 Pro"
          xcrun simctl install booted ./ios/build/Build/Products/Release-iphonesimulator/MapLibreReactNativeExample.app

      - name: Test with Maestro
        working-directory: ./packages/react-native-app
        run: maestro test e2e/show-map.yml
